# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-05 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsposts',
            old_name='authorfirstname',
            new_name='applylink',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='authorbg',
            new_name='companydescription',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='authorcontact',
            new_name='companywebsite',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='authordesignation',
            new_name='jobdescription',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='posttitle',
            new_name='jobtitle',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='authorlastname',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='jobsposts',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='jobsposts',
            name='postcontent',
        ),
        migrations.RemoveField(
            model_name='jobsposts',
            name='postsummary',
        ),
    ]
