# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181105_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsposts',
            name='companyname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
