# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsposts_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsposts',
            name='requiredexperience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobsposts',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
