# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20181106_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsposts',
            name='salary',
            field=models.TextField(null=True),
        ),
    ]
