# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cposttitle', models.CharField(max_length=200)),
                ('cpostsummary', models.TextField(null=True)),
                ('cpostcontent', models.TextField(null=True)),
                ('ccreated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='collegeposts/')),
                ('cauthorfirstname', models.CharField(max_length=200, null=True)),
                ('cauthorlastname', models.CharField(max_length=200, null=True)),
                ('cauthorbg', models.TextField(null=True)),
                ('cauthordesignation', models.TextField(null=True)),
                ('cauthorcontact', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'BlogPosts',
            },
        ),
    ]
