# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-24 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeposts',
            options={'verbose_name_plural': 'CollegePosts'},
        ),
    ]
