# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-15 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttitle', models.CharField(max_length=200)),
                ('postcontent', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogposts/')),
                ('authorname', models.CharField(max_length=200)),
                ('authorbg', models.TextField()),
                ('authorcontact', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'BlogPosts',
            },
        ),
    ]
