# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='authorname',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='authorfirstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='authorlastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
