# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181023_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='authordesignation',
            field=models.TextField(null=True),
        ),
    ]
