# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogposts_authordesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='postsummary',
            field=models.TextField(null=True),
        ),
    ]
