# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogposts_postsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='authorbg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='authorcontact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='postcontent',
            field=models.TextField(null=True),
        ),
    ]
